### ISSUE TITLE
.Scan() panics if a time.Time mock value is scanned into a sql.NullTime

### ISSUE THREAD

**Issue by wttw** [pashagolub/pgxmock#102]
**Describe the bug**
rowSets.Scan() tries to use reflect.Set to scan from one struct to another, regardless of whether they're compatible.

**To Reproduce**

```
        mock.ExpectQuery(`SELECT now()`).
		WillReturnRows(
			mock.NewRows([]string{"stamp"}).
				AddRow(time.Now()))

	var value sql.NullTime
	err: = mock.QueryRow(context.Background(), `SELECT now()`).Scan(&value)
```

I would expect the sql.NullTime value be set to time.Now().

Instead it panics during the Scan, with 

```
panic: reflect.Set: value of type time.Time is not assignable to type sql.NullTime [recovered]
	panic: reflect.Set: value of type time.Time is not assignable to type sql.NullTime
```

and a stack trace pointing at [pgxmock/rows.go:92](https://github.com/pashagolub/pgxmock/blob/9be33e0f1925a8572f2deae43e09a513859db1c9/rows.go#L92)

I don't think comparing Kind() is enough to decide that a value is assignable. If we were to attempt to use .Scan() on the destination variable first that would likely work for many cases that fail via reflect.Set().

**Comment by pashagolub** [comment]
Thanks for noticing. 

The developer should carefully form the row they are trying to return. In your case, the proper way would be:

```go
        mock.ExpectQuery(`SELECT now()`).
		WillReturnRows(
			mock.NewRows([]string{"stamp"}).
				AddRow(sql.NullTime{time.Now(),true}))

	var value sql.NullTime
	err: = mock.QueryRow(context.Background(), `SELECT now()`).Scan(&value)
```

The rule is simple: You're expecting what you've sent. `pgxmock` is not a comprehensive connection library but a simple and efficient mocking one. You mock; your responsibility to mock it right.
