### ISSUE TITLE
pgxmock.AddRows makes []bytes conversion panic

### ISSUE THREAD

**Issue by sejin-P** [pashagolub/pgxmock#128]
**Describe the bug**
I applied pgx.CollectRows and pgx.RowToAddrOfStructByPos to simplify sql query logic.
Like this:
`pgx.CollectRows(rows, pgx.RowToAddrOfStructByPos[{{mymodel struct}}]`
Then I tested the function logic which contains above line, it panicked and a message was:
`panic: interface conversion: interface {} is string, not []uint8`

**To Reproduce**
1. Just I described bug, you can reproduce when you use pgx.CollectRows and pgx.RowToaddrOfStructByPos
2. Then use pgxmock.AddRow in the test code.

**Expected behavior**
Not panicking

**Screenshots**
<img width="620" alt="image" src="https://user-images.githubusercontent.com/42539506/223687579-8dc94d5f-3ab1-4645-8d49-1efd69fedac3.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1
 - Browser chrome
 - Versio 108.0.5359.124 (Official Build) (arm64)

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro
 - OS: iOS 16.1
 - Browser chrome
 - Version Version 110.0.5481.114

**Additional context**
Conversion to bytes slice with considering type would resolve this issue. I will fix this issue when I have some time to get it. Thank you.

**Comment by pashagolub** [comment]
Would you please provide a reproducible example? I cannot reproduce the bug even though I'm using `CollectRows` in some tests

**Comment by sejin-P** [comment]
@pashagolub Did you use `RowToAddrOfStructByPos`? `RowToAddrOfStructByPos` caused that bug. I checked this reason by analyzing the implementation of `RowToAddrOfStructByPos` and pgxmock.AddRow.

**Comment by pashagolub** [comment]
Dear @sejin-P, 

I'm buried under ongoing tasks at the moment. A code snippet showing the issue may help.

Thanks for understanding.

**Comment by sejin-P** [comment]
I understand your hardship. I cannot provide raw code snippet, but I'm going to show you similar a code snippet.
`func ListModel(ctx context.Context, id string) ([]*Model, error) {
	query := "SELECT * FROM model WHERE id = $1"
	rows, err := sql.DB.Query(ctx, query, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	models, err := pgx.CollectRows(rows, pgx.RowToAddrOfStructByPos[Model])
	if err != nil {
		return nil, sql.HandleError(err)
	}

	~~~
}`

And I test it in my unit test code with using pgxmock's expect query.

`mockDB.ExpectQuery("SELECT [*] FROM model WHERE id = [$]1").
			WithArgs("id").
			WillReturnRows(pgxmock.NewRows([]string{"~~ some model columns~~~"}).
				AddRow(some rows~~~))
`

And its error log was just like this:
panic: interface conversion: interface {} is string, not []uint8 [recovered]
	panic: interface conversion: interface {} is string, not []uint8

**Comment by sejin-P** [comment]
I understand your hardship. I cannot provide raw code snippet, but I'm going to show you similar a code snippet.
`func ListModel(ctx context.Context, id string) ([]*Model, error) {
	query := "SELECT * FROM model WHERE id = $1"
	rows, err := sql.DB.Query(ctx, query, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	models, err := pgx.CollectRows(rows, pgx.RowToAddrOfStructByPos[Model])
	if err != nil {
		return nil, err
	}

	~~~
}`

And I test it in my unit test code with using pgxmock's expect query.

`mockDB.ExpectQuery("SELECT [*] FROM model WHERE id = [$]1").
			WithArgs("id").
			WillReturnRows(pgxmock.NewRows([]string{"~~ some model columns~~~"}).
				AddRow(some rows~~~))
`

And its error log was just like this:
panic: interface conversion: interface {} is string, not []uint8 [recovered]
	panic: interface conversion: interface {} is string, not []uint8

**Comment by sejin-P** [comment]
In my opinion, pgxmock's RawValues() implementation causes this panic:
https://github.com/pashagolub/pgxmock/blob/857ea5477207f597478d20825f7230fd04bdce31/rows.go#L130

When using pgx's `RowToAddrOfStructByPos`, it calls RawValues() func:
https://github.com/jackc/pgx/blob/be79f1c8f598cdc93eb77158fe631e96bc591b7d/rows.go#L520

In pgxmock's RawValues implementation, converting some types into []bytes causes panic except for string. Therefore, we should fix it. I'll actively participate in resolving this issue.

Thank you for your effort, @pashagolub

**Comment by Eitol** [comment]
see: [](https://github.com/pashagolub/pgxmock/pull/137)
