### ISSUE TITLE
Rows does not correctly works for QueryRow

### ISSUE THREAD

**Issue by janisz** [pashagolub/pgxmock#133]
**Describe the bug**
Rows does not correctly works for QueryRow.

**To Reproduce**

```
pgxRows := pgxpoolmock.NewRows([]string{"server_version"}).AddRow("15.1").ToPgxRows()
pgxRows.Next() // This line is necessary to prevent panic during Scan.
db.EXPECT().QueryRow(gomock.Any(), "SHOW server_version;").Return(pgxRows)
```

```
github.com/driftprogramming/pgxpoolmock.(*rowSets).Scan(0x41ee87?, {0xc000b5e820?, 0x2cac0a0?, 0x3933e01?})
go/pkg/mod/github.com/driftprogramming/pgxpoolmock@v1.1.0/rows.go:69 +0x5f0
```

**Expected behavior**
Add `Row` struct that will correctly implement `pgx.Row` interface.

**Comment by pashagolub** [comment]
Hello. Would you please provide a complete example to test?

What is `pgxpoolmock`? What is `gomock`?

**Comment by janisz** [comment]
My bad wrong repo :) I've tested pgxpoolmock and pxgxmock

**Comment by pashagolub** [comment]
Ah! I see. No problem. Shit happens. :)
