### ISSUE TITLE
Add missing methods to PgxPoolIface

### ISSUE THREAD

**Issue by TulioGuaraldoB** [pashagolub/pgxmock#139]
# Add missing methods from PgxPoolIface to current *pgxpool.Pool (v5)

Hey, hope everyone is doing fine! I just made some adjustments to match the missing methods when mocking pgxpool.
I've already spoken to pasha, and he said to open the PR, but before I need permission to push to the new branch I've created...
Thank you!

**Comment by pashagolub** [comment]
Sorry. I don't get it. What permissions do you need?

Just fork the repo, create a branch in your fork, then create a pull request.

**Comment by TulioGuaraldoB** [comment]
Oh, I just have some problems yesterday from random git confis on my machine too hehe, sorry for the misunderstood, Pasha.
Here is my PR for the changes I've spoken to, thank u!

https://github.com/pashagolub/pgxmock/pull/140
