### ISSUE TITLE
Deallocate is not part of a connection pool

### ISSUE THREAD

**Issue by ConsoleTVs** [pashagolub/pgxmock#143]
**Describe the bug**
Can't mock a connection pool due `Deallocate()` method on `pgxIface`.

The connection pool lacks this method: https://pkg.go.dev/github.com/jackc/pgx/v5/pgxpool#Pool

**To Reproduce**

```go
func DoSomething(pool pgxmock.PgxPoolIface) {
	// ...
}

pool, _ := pgxpool.New(context.Background(), url)
DoSomething(pool) // fails.
```

**Expected behavior**
The pool / mock to work.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser: No
 - PGX Version: 5
 - PGXMock Version: 2

**Comment by pashagolub** [comment]
Hey, are you trying to use `pgxmock.pgxIface` in a test case or in the production code?

**Comment by ConsoleTVs** [comment]
I have a set of functions that need a database connection. To make those functions testable, I tried making use of the interface, but quickly noticed that a real connection could not be passed it. How else would you do this?

**Comment by pashagolub** [comment]
Let me ask again. Are those functions for testing? Are they begin with `Test...`? 
Because one shouldn't use `pgxmock.pgxIface` in production code. That's why it's defined as local with the lowercase first letter. Even if I would add the missing function declaration, I want to warn you about proper use case.

So one can define their own interfaces and use them instead, see [example](https://github.com/pashagolub/pgxmock/blob/master/examples/basic/basic.go).

**Comment by ConsoleTVs** [comment]
In the example I provided, DoSomething is clearly not in a test.
Furthermore, the interface I used is: https://github.com/pashagolub/pgxmock/blob/v2.8.0/pgxmock.go#L134 that uses the private interface and it is marked as public. I have updated the example.

**Comment by pashagolub** [comment]
ok, my bad. I see now. Do you want to create a PR with this change maybe?

**Comment by ConsoleTVs** [comment]
> ok, my bad. I see now. Do you want to create a PR with this change maybe?

Can do this. Either way, perhaps separating all the interface methods to each specific instance (Conn & Pool) would make more sense as Conn still have Deallocate().

Do you find it an acceptable solution to move the methods to each interface individually and get rid of pgxIface?

**Comment by pashagolub** [comment]
Well, I think it can save us some space since `pool` and `conn` have a lot of common. But if the code become pretty and shiny, no objections from my side :)
