### ISSUE TITLE
Starting using pgxmock

### ISSUE THREAD

**Issue by zargex** [pashagolub/pgxmock#18]
Hi, I just started to use pgxmock to write my unit tests, but I don't really understand how I can test these two
kind of queries:

1. "CREATE TABLE foo(id serial, bar int) IF NOT EXISTS" 
2. "INSERT INTO foo(bar) VALUES (1) RETURNING id"

For the first one, my test always pass. For the later one, it always fails (I think the issue here is that I don't know the id before the insert so I don't know how can be compared).

Thanks

**Comment by pashagolub** [comment]
Hey, would you please show the tests?

**Comment by zargex** [comment]
Yeah, this is are the two tests
```
func TestCreateTable(t *testing.T) {
	mock, err := pgxmock.NewConn()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	defer mock.Close(context.Background())
	mock.ExpectExec("CREATE TABLE IF NOT EXISTS maps").WillReturnResult(pgxmock.NewResult("CREATE TABLE", 0))

	// now we execute our method
	_, err = create_maps(mock, context.Background())
	if err != nil {
		t.Errorf("error was not expected while creating table: %s", err)
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expectations: %s", err)
	}
}

func TestInsertGroup(t *testing.T) {
	mock, err := pgxmock.NewConn()
	if err != nil {
		t.Fatalf("an error '%s' was not expected when opening a stub database connection", err)
	}
	defer mock.Close(context.Background())
	mock.ExpectQuery("INSERT INTO group").WithArgs("test")

	// now we execute our method
	_ = insert_group(mock, context.Background(), "test")
	if err != nil {
		t.Errorf("error was not expected while creating table: %s", err)
	}

	if err := mock.ExpectationsWereMet(); err != nil {
		t.Errorf("there were unfulfilled expectations: %s", err)
	}
}
```

**Comment by pashagolub** [comment]
And what are errors? :-D

**Comment by zargex** [comment]
Ok, this is embarrassing, but now it doesn't give me an error :/ .
However in the first test, if I change
 `pgxmock.NewResult("CREATE TABLE", 0)`

  for something like: 
 `pgxmock.NewResult("INSERT", 1 )`

It doesn't give me any error. Not sure why

**Comment by pashagolub** [comment]
Well, it shouldn't. in `pgx` the result is simply a text followed by an optional number describing success status. So until you check the result string you won't get any error.

I hope I explained well.

If you want to emulate error you should explicitly say so, e.g. `WillReturnError(fmt.Errorf("some error"))``.
