### ISSUE TITLE
pgxmock.ExpectBegin is not documented

### ISSUE THREAD

**Issue by MikeTaylor** [pashagolub/pgxmock#181]
I expected to see it in the **Functions** section at
https://pkg.go.dev/github.com/pashagolub/pgxmock/v3#pkg-functions
but only `NewResult` and `QueryMatcherOption` are listed here.

I can't find it anywhere else in the documentation, either.

(BTW., thanks for a really helpful module!)

**Comment by pashagolub** [comment]
Well, it's here https://pkg.go.dev/github.com/pashagolub/pgxmock/v3#ExpectedBegin

The manual looks this way probably because interface is not documented. I'll check what can we do about this

**Comment by MikeTaylor** [comment]
Thanks for looking into this, @pashagolub. I'm a total newbie with pgxmock, and indeed pgx, so this probably reflects my ignorance more than anything, but I would have expected to see something about the function that _creates_ an object of type `ExpectedBegin` as well as documentation of the resulting type.

**Comment by pashagolub** [comment]
ok, that is how `go doc` system works. It ignores public methods if they are not implemented by public struct in the package. [sqlmock](https://pkg.go.dev/github.com/DATA-DOG/go-sqlmock) has the same issue. I'm not sure, how to fix this problem without breaking the code completely.

**Comment by MikeTaylor** [comment]
Hmm, that sounds like a bug in `go doc` to me, but that's obviously not your fault!

Maybe the workaround is to add a description of the interface methods in the text overview?

**Comment by pashagolub** [comment]
Not a bug but a feature. :-)

It seems I can put interface into doc. Let me try something.

**Comment by MikeTaylor** [comment]
Thanks for handling this!
