### ISSUE TITLE
When you close row, the test will panic

### ISSUE THREAD

**Issue by MeelyNe** [pashagolub/pgxmock#190]
**Describe the bug**
pgxmock.Rows returns panic if business code closes it

**To Reproduce**
```go

// type of replicatePool is pgxpool.Pool{}

rows, err := i.replicaPool.Query(ctx, query, id)
if err != nil {
	return nil, fmt.Errorf("error on query: %w", err)
}
defer rows.Close() // here fails
```

on test:
```go
rows := pgxmock.NewRows([]string{"id"}).
		AddRow(1).
		AddRow(2)

rows.CloseError(nil)

replicaPool.EXPECT().Query(ctx, gomock.Any(), id).Return(rows.Kind(), nil)
```

**Expected behavior**
not panic )

**Version**
github.com/jackc/pgx/v5 v5.5.2
github.com/pashagolub/pgxmock/v3 v3.3.0

**Console Output**

  [PANICKED] Test Panicked
  In [It] at: /usr/local/go/src/runtime/panic.go:261 @ 02/14/24 16:39:15.544

  runtime error: invalid memory address or nil pointer dereference

  Full Stack Trace
    github.com/pashagolub/pgxmock/v3.(*rowSets).Close(0xc000387d28?)
    	/home/username/GolandProjects/myProject/vendor/github.com/pashagolub/pgxmock/v3/rows.go:53 +0x4

**Comment by pashagolub** [comment]
This is not `pgxmock` code. What is `EXPECT()`? What is `gomock` anyway?

**Comment by MeelyNe** [comment]
> This is not `pgxmock` code. What is `EXPECT()`? What is `gomock` anyway?

I use github.com/uber-go/mock, cuz we use wrapper around default `pgxpool.Pool` . But I was thinking of using use your library just for mock rows )

**Comment by pashagolub** [comment]
No, sorry. That doesn't work that way )

**Comment by MeelyNe** [comment]
OK :( I'm sorry, can you recommend an alternative? (
