### ISSUE TITLE
panic when calling rows.Values()

### ISSUE THREAD

**Issue by labi-le** [pashagolub/pgxmock#195]
https://github.com/pashagolub/pgxmock/blob/f9f4e9f5b8304f33de41622eb17be5566156a26f/rows.go#L69

panic: runtime error: index out of range [-1]

i noticed that the error doesn't occur **when I call rows.Next()**, but in this case study I don't need to call this method	

```go
func TestObject_ScanRow(t *testing.T) {
	dat := _testPrepareData(1)
	prepared := _map2Rows(dat)

	o := NewObject(scanner.NewDynamic('_', []string{"to", "data"}))
	err := o.ScanRow(prepared)
	if err != nil {
		t.Fatal(err)
	}

	if len(o.Data) < 3 {
		t.Fatal("not equal")
	}
}

// func _map2Rows(data []map[string]string) pgx.Rows

// func _testPrepareData(length int) []map[string]string

```

**Comment by pashagolub** [comment]
Would you please provide reproducible test case showing the issue, that I can run on my environment?

**Comment by labi-le** [comment]
> Would you please provide reproducible test case showing the issue, that I can run on my environment?

```go
package object_test

import (
	"github.com/jackc/pgx/v5"
	"github.com/pashagolub/pgxmock/v3"
	"testing"
)

func _map2Rows(data []map[string]string) pgx.Rows {
	var keys = make([]string, 0, len(data[0]))
	for key := range data[0] {
		keys = append(keys, key)
	}

	mock, _ := pgxmock.NewPool()

	rows := mock.NewRows(keys)
	values := make([]interface{}, len(keys))
	for _, row := range data {
		for kl := 0; kl < len(keys); kl++ {
			key := keys[kl]
			values[kl] = row[key]
		}

		rows.AddRow(values...)
		clear(values)
	}

	return rows.Kind()
}

type testObject struct {
	ID int
}

func (o *testObject) ScanRow(rows pgx.Rows) error {
	//rows.Next()
	_, rowErr := rows.Values()
	if rowErr != nil {
		return rowErr
	}

	return nil
}

func TestObjects_ScanRow(t *testing.T) {
	rows := _map2Rows([]map[string]string{
		{
			"id": "1",
		},
		{
			"id": "2",
		},
	})
	o := testObject{}
	err := o.ScanRow(rows)
	if err != nil {
		t.Fatal(err)
	}
}

```

**Comment by pashagolub** [comment]
I don't see here any testing. What are you trying to achieve? 

And by the way, `rows.Next()` [**must be called**](https://pkg.go.dev/github.com/jackc/pgx/v5#Rows):

>// Values returns the decoded row values. As with Scan(), **it is an error to
	// call Values without first calling Next()** and checking that it returned
	// true.
	Values() ([][any](https://pkg.go.dev/builtin#any), [error](https://pkg.go.dev/builtin#error))

**Comment by labi-le** [comment]
> I don't see here any testing. What are you trying to achieve?
> 
> And by the way, `rows.Next()` [**must be called**](https://pkg.go.dev/github.com/jackc/pgx/v5#Rows):
> 
> > // Values returns the decoded row values. As with Scan(), **it is an error to
> > // call Values without first calling Next()** and checking that it returned
> > // true.
> > Values() ([][any](https://pkg.go.dev/builtin#any), [error](https://pkg.go.dev/builtin#error))

when the database returns only one record and there is a Next() call, the error rows is closed is returned

**Comment by pashagolub** [comment]
> when the database returns only one record and there is a Next() call, the error rows is closed is returned

Would you please provide me with the simplest code snippet showing this issue?

Thanks in advance!

**Comment by labi-le** [comment]
> Would you please provide me with the simplest code snippet showing this issue?

the error will occur if I use rows.Next() in the ScanRow method.

```go
package main

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"log"
	"os"
)

func main() {
	config, _ := pgx.ParseConfig("dsn")
	config.DefaultQueryExecMode = pgx.QueryExecModeSimpleProtocol

	conn, err := pgx.ConnectConfig(context.TODO(), config)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Unable to connection to database: %v\n", err)
		os.Exit(1)
	}

	pf := Profile{}
	if testErr := conn.QueryRow(context.Background(), "select 1 as id, 'ivan' as name").Scan(&pf); testErr != nil {
		log.Fatal(testErr)
	}
}

type Profile struct {
}

func (p *Profile) ScanRow(rows pgx.Rows) error {
	//rows.Next()
	values, err := rows.Values()
	if err != nil {
		return err
	}

	_ = values

	return rows.Err()
}

```

**Comment by pashagolub** [comment]
Would you please check #196?

This should work:
```terminal
go get -u github.com/pashagolub/pgxmock/v3@195-panic-when-calling-rowsvalues
```

**Comment by labi-le** [comment]
> Would you please check #196?

there's still panic in the tests
in the previous example, the panic has disappeared

**Comment by pashagolub** [comment]
In which exactly tests? Would you please add code showing the issue

**Comment by labi-le** [comment]
> In which exactly tests? Would you please add code showing the issue

https://github.com/pashagolub/pgxmock/issues/195#issuecomment-2023355534

**Comment by pashagolub** [comment]
That code **must use** `rows.Next()`.

Why? Because you are playing with low level structs and interfaces. Thus you are responsible for correct usage.

Now can you, please, provide a code showing a real life problem, meaning when we are really testing database code?

**Comment by pashagolub** [comment]
```go
func TestObjects_ScanRow(t *testing.T) {
	rows := _map2Rows([]map[string]string{
		{
			"id": "1",
		},
		{
			"id": "2",
		},
	})
	o := testObject{}
	rows.Next()
	err := o.ScanRow(rows)
	if err != nil {
		t.Fatal(err)
	}
}
```

**Comment by labi-le** [comment]
honestly it's so unimportant, i'll just redo the test. thanks for wasting your time on this mess
