### ISSUE TITLE
Problem getting rows to return

### ISSUE THREAD

**Issue by AshMcConnell** [pashagolub/pgxmock#213]
Hi @pashagolub 

Sorry, I am a bit of a newbie to Go and to pgxmock.  I can't seem to get it to return any rows.

Here is the function I am testing:- 

```go
func (crud *DbCrud[T]) SingleRow(tableName string, id string) (*T, error) {
	caser := cases.Title(language.English)

	rows, _ := crud.Pool.Query(context.Background(), "SELECT * FROM race_stats."+tableName+" WHERE id = $1", id)

	entity, err := pgx.CollectOneRow(rows, pgx.RowToStructByNameLax[T])
	if err != nil {
		return nil, SingleErrorHandler(err, caser.String(tableName), id, "Fetching "+tableName)
	}
	return &entity, nil
}
```

Here is my test function: -

```go
func TestSingleRow_Success(t *testing.T) {
	mockPool, _ := pgxmock.NewPool()
	mockLog := &mocks.MockLogger{}

	rows := pgxmock.NewRows([]string{"id", "name"}).AddRow(int64(1), "thing")

	mockPool.ExpectQuery("SELECT * FROM race_stats.thing WHERE id = $1").
		WithArgs("1").
		WillReturnRows(rows)

	dbCrud := NewDbCrud[Thing](mockPool, mockLog)

	dbCrud.SingleRow("thing", "1")
}
```

I've debugged and rows is always returning nil.  I've tried wrapping it in a ExpectBegin / ExpectCommit, but no luck.  Is it not matching the SQL / args or am I doing something else wrong?

Thanks for your help!
Ash

**Comment by AshMcConnell** [comment]
Ah, the rubber 🦆 strikes again.

I realised that ExpectQuery uses a regex to match.  I'll figure out how to escape the * (and perhaps the $?)

Thanks!
Asjh

**Comment by pashagolub** [comment]
You can [change](https://pkg.go.dev/github.com/pashagolub/pgxmock/v4#readme-customize-sql-query-matching) how you match a query. You can even write your own matcher :)
