### ISSUE TITLE
Implement CopyFrom using pgxmock

### ISSUE THREAD

**Issue by machytkafitanalytics** [pashagolub/pgxmock#22]
This is more a question. I could not find any working example of how to test CopyFrom command using pgxmock. Is it possible? If so is there some example of how to do it?

**Comment by pashagolub** [comment]
Hello. Not right now, it's still in TODO list.

As you can see there are already templates for `pgx` specific methods: https://github.com/pashagolub/pgxmock/blob/10a6553866bb9c687750953da69fa38f369bea34/pgxmock.go#L237

PR are always welcome

**Comment by pashagolub** [comment]
Would you please try #23 if that suits your needs?

Thanks in advance
