### ISSUE TITLE
feat: support using pgxmock with stdlib.OpenDBFromPool

### ISSUE THREAD

**Issue by rbtcollins** [pashagolub/pgxmock#221]
**Is your feature request related to a problem? Please describe.**
I want to use bob with pgx, and test it. bob needs a stdlib.OpenDBFromPool as far as I call; so then when I want to test I can create a pgxmock, but I can't convert it to a *sql.DB (which bob.NewDB takes) or alternatively a bob.Queryer.

**Describe the solution you'd like**
Either a collaborating Mock that implements sql.DB, or perhaps a change to pgx to take an interface, not a struct, to OpenDBFromPool

**Describe alternatives you've considered**

**Additional context**

**Comment by pashagolub** [comment]
Whats is bob?

**Comment by rbtcollins** [comment]
https://github.com/stephenafamo/bob

**Comment by pashagolub** [comment]
And how do you use it?
