### ISSUE TITLE
Incompatibility with sqlmock

### ISSUE THREAD

**Issue by leventov** [pashagolub/pgxmock#30]
**Is your feature request related to a problem? Please describe.**

`sqlmock` does some value conversions for the user, for example:

 - Scanned `*float64` from `float64` value supplied in `AddRow()`
 - Scanned `[]byte` from `string` value supplied in `AddRow()`

pgxmock is more strict, not supporting any "obvious" conversions.

**Comment by pashagolub** [comment]
Hello,

thanks for your request. Is this something that can be fixed by #29?

PRs are always welcome if you know for sure what we lack here.

Regards.

**Comment by pashagolub** [comment]
Closed due inactivity
