### ISSUE TITLE
Support for JSONB

### ISSUE THREAD

**Issue by mynyml** [pashagolub/pgxmock#43]
**Is your feature request related to a problem? Please describe.**
I have a jsonb column that pgx supports out of the box. However there's no way I know of to tell pgxmock that a value in AddRow() is of type json/jsonb. I tried wrapping it with pgtype.JSONB without success (got `panic: reflect.Set: value of type pgtype.JSONB is not assignable to type Config`).

**Describe the solution you'd like**
Built-in support for json/jsonb columns.

It might well be the case that there's already a known alternative for this, in which case the feature request would be to add it to the documentation for this project.

**Comment by pashagolub** [comment]
📅 I'm closing this outdated issue.

♻️ If you think there is new information allowing us to address the issue, please reopen it and provide us with updated details.

🤝 Thanks in advance.

**Comment by pinguinjkeke** [comment]
Facing the same problem here:
```go
type MyStruct struct {
    ID int64
    Name string
    Statistics MyStats
}

type MyStats struct {
    Color string `json:"color"`
    Size 5 `json:"size"`
}

mock.
    ExpectQuery("SELECT id, name, statistics_jsonb FROM something").
    WillReturnRows(
        pgxmock.NewRows([]string{"id", "name", "statistics_jsonb"}).
            AddRow(int64(1), "hello", `{"color": "red", "size": 5}`)
    )
```

`Statistics` struct field will get automatically unmarshalled with pgx via `RowToAddrOfStructByName` and other mappers while `pgxMock` does not support it

**Comment by pashagolub** [comment]
Would you please provide full test case showing the error?
