### ISSUE TITLE
Add BeginTx in pgxIface

### ISSUE THREAD

**Issue by serhiy-v** [pashagolub/pgxmock#47]
Hi, my code is using ```BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)``` function, and i can't use mock with it, because this func is not implemented in **pgxIface**. While exploring code of pgxmock I find out that function **BeginTx** is already exist:
```go
func (c *pgxmock) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ex, err := c.begin(txOptions)
	if ex != nil {
		time.Sleep(ex.delay)
	}
	if err != nil {
		return nil, err
	}

	return c, nil
}
```
Is it ok that this func is not implemented in **pgxIface**? Or maybe there is some other way of working with this func?

**Comment by pashagolub** [comment]
Hi, 

thanks for noticing. Yeap, this issue should be addressed. Seems like I just forgot to update the interface declaration.

**Comment by avshvetz** [comment]
Hi, I have the same issue. I've prepared PR, please let me know if I need to do additional changes 
https://github.com/pashagolub/pgxmock/pull/48
