### ISSUE TITLE
Support for `SendBatch`

### ISSUE THREAD

**Issue by knation** [pashagolub/pgxmock#52]
**Is your feature request related to a problem? Please describe.**
Missing functionality in mock: `SendBatch` currently just returns a nil object [see here](https://github.com/pashagolub/pgxmock/blob/558cc24511bc3a9a7e36fc5ce371bf31c49a29e6/pgxmock.go#L403). This does not allow for mocking or testing inputs.

**Describe the solution you'd like**
Implement [`SendBatch`](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.SendBatch) on basic connection and pools. Additionally, create a `mock.ExpectSendBatch` function to test `SendBatch` calls in code.

**Describe alternatives you've considered**
Considering changing my code to not use `SendBatch` just to be able to better test expectations.

**Additional context**
None

**Comment by pashagolub** [comment]
Hello. Thanks a lot for your proposal.

I don't remember why I didn't implement this functionality in the first place. I'll try to get back to it ASAP.

If you have an opportunity to provide a pull request for this feature, that would be awesome.

Thanks

**Comment by LionelCS** [comment]
Hello, I am interested in this feature too.

**Comment by sejin-P** [comment]
Is there any news about this feature?

**Comment by pashagolub** [comment]
Hey. Thanks for you interest. I've paused work on this feature due to support of a new major pgx release and a lack of free time.

Feel free to provide a pull request for a review.

Merry Christmas and a happy New year

**Comment by sejin-P** [comment]
Ok I will try to support this feature by contribution. Thank you for your answer and happ new year!
