### ISSUE TITLE
Unable to scan to uint64 or other standard base types

### ISSUE THREAD

**Issue by aaranmcguire** [pashagolub/pgxmock#62]
**Describe the bug**

It seems the mock system fails to scan to base types if the `Scan()` doesn't return the *exact* type as the destination value. For example, this query returns a `int`, but while it can convert to `uint` it seems the `Scan()` can't convert it. I'd expect this for custom types, but not base types. Could you put me in the right direction to fix this?

The code causing the issue is [here](https://github.com/pashagolub/pgxmock/blob/master/rows.go#L93-L105).

I've created the following test:

```go

func TestThisStrangeIssue(t *testing.T) {
	mock, err := pgxmock.NewPool()
	if err != nil {
		panic(err)
	}

	mock.ExpectQuery("SELECT .+ FROM test WHERE .+").
		WithArgs(1).
		WillReturnRows(pgxmock.NewRows(
			[]string{"id"}).
			AddRow(1),
		)

	rows := mock.QueryRow(context.Background(), "SELECT id FROM test WHERE id = $1", 1)

	var id uint64
	err = rows.Scan(&id)
	if err != nil {
		t.Error(err)
	}
}
```

Which returns:

```
--- FAIL: TestThisStrangeIssue (0.00s)
    /~/hello_test.go:65: Destination kind 'uint64' not supported for value kind 'int' of column 'id'
```

**Comment by pashagolub** [comment]
Hello, 

Just a quick guess. Can we use explicit type casting here, e.g.
```go
	mock.ExpectQuery("SELECT .+ FROM test WHERE .+").
		WithArgs(int64(1)).
		WillReturnRows(pgxmock.NewRows(
			[]string{"id"}).
			AddRow(int64(1)),
		)
```
Cannot check it right now. Let me know if this helps

**Comment by aaranmcguire** [comment]
Sadly not. It's the same error.
I did find adding the following fixed the issue, but I don't fully know the impact to this change:

```go
} else if val.Type().ConvertibleTo(reflect.Indirect(destVal).Type()) {
			dv := reflect.Indirect(destVal)
			dv.Set(val.Convert(dv.Type()))
```

**Comment by pashagolub** [comment]
Would you please provide the exact method you were patching?

Thanks in advance

**Comment by aaranmcguire** [comment]
Added it just above this highlighted part: https://github.com/pashagolub/pgxmock/blob/master/rows.go#L93-L105

**Comment by pashagolub** [comment]
I checked my workaround and spotted I used the wrong type! 🤦

This is the way to go:
```go
func TestThisStrangeIssue(t *testing.T) {
	mock, err := NewPool()
	if err != nil {
		panic(err)
	}

	mock.ExpectQuery("SELECT .+ FROM test WHERE .+").
		WithArgs(uint64(1)).
		WillReturnRows(NewRows(
			[]string{"id"}).
			AddRow(uint64(1)),
		)

	rows := mock.QueryRow(context.Background(), "SELECT id FROM test WHERE id = $1", uint64(1))

	var id uint64
	err = rows.Scan(&id)
	if err != nil {
		t.Error(err)
	}
}
```

I don't want to add a check for `ConvertibleTo` because this is not how the `pgx` itself works. And we are trying to mock the native pgx behavior.

**Comment by aaranmcguire** [comment]
Ah, I see. The type in `AddRow(uint64(1))` must match the destination type during the scan. This is different to [DATA-DOG/go-sqlmock](https://github.com/DATA-DOG/go-sqlmock), but that's fine.

Thanks for helping.
