### ISSUE TITLE
Error `Destination kind 'interface' not supported for value kind '<int64>' of column '<column>'`

### ISSUE THREAD

**Issue by rubenhazelaar** [pashagolub/pgxmock#73]
**Describe the bug**
Cannot use *interface{} as type to use in Scan when use pgxmock, this results in the error below:

`Destination kind 'interface' not supported for value kind '<int64>' of column '<column>'`

**To Reproduce**
Some code snippets to reproduce the behavior:

If you have (like I have) an implementation which uses a variable with type *interface{} to scan a values.
```
var value any
err = r.QueryRow(ctx, q, args...).Scan(&value)
if err != nil {
   return
}
```

usage of pgxmock
```
mock.ExpectQuery(`SELECT 123`).
	WillReturnRows(
		mock.NewRows([]string{"id"}).
			AddRow(int64(123)))  // Value which should be scanned in *interface{}
``` 

**Expected behavior**
interface should contain the value of type int64 containing `123`  without an error being throwed.

I think the following line plays a role in the behavior:

LINE 86: `if destVal.Elem().Kind() == val.Kind() {`

If the condition in this line is false, a last step is done to trying to use the Scanner interface (which *interface{} does not have), subsequently the error is triggered.

When looking at how the standard library deals with this with a type switch (database/sql/convert.go).
See specifically the last case where *any/*interface{} is dealt with. This logic is part of the `convertAssignRows`  function. 

Do you have any specific ideas on how to handle *interface{}? 

```
        switch d := dest.(type) {
	case *string:
		sv = reflect.ValueOf(src)
		switch sv.Kind() {
		case reflect.Bool,
			reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
			reflect.Float32, reflect.Float64:
			*d = asString(src)
			return nil
		}
	case *[]byte:
		sv = reflect.ValueOf(src)
		if b, ok := asBytes(nil, sv); ok {
			*d = b
			return nil
		}
	case *RawBytes:
		sv = reflect.ValueOf(src)
		if b, ok := asBytes([]byte(*d)[:0], sv); ok {
			*d = RawBytes(b)
			return nil
		}
	case *bool:
		bv, err := driver.Bool.ConvertValue(src)
		if err == nil {
			*d = bv.(bool)
		}
		return err
	case *any:
		*d = src
		return nil
	}
```

**Additional context**
Both pgx (see: https://github.com/jackc/pgx/issues/769) and https://github.com/DATA-DOG/go-sqlmock support this behavior.

**Comment by rubenhazelaar** [comment]
Ran my test with `github.com/pashagolub/pgxmock@73_accept_any_interface_in_Scan` and this solves the problem, great! 

Seeing that I will depend on pgx in the future more and more (and I think more and more people will), I suspect I will be using pgxmock more as well, thank you for your efforts. I don't see any mention on https://github.com/jackc/pgx, would be a nice addition :).

I think we can close this one

**Comment by pashagolub** [comment]
thanks a lot for your kind words!
