### ISSUE TITLE
pgxmock.NewPool and empty result set: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by NickBelhomme** [pashagolub/pgxmock#77]
**Describe the bug**
When testing results sets with NO rows we get an out of range error.

**To Reproduce**
This should also happen in the blog api example.
https://github.com/pashagolub/pgxmock/blob/master/examples/blog/blog_test.go#L120

What I do is:
```mockRead.ExpectQuery(".*").WillReturnRows(pgxmock.NewRows([]string{"value"}))```

This produces the error on line:
https://github.com/pashagolub/pgxmock/blob/master/rows.go#L72

Current result set value:
![2022-06-03_10-12](https://user-images.githubusercontent.com/312003/171815553-1d702536-86bb-4052-bf2a-ca68a4636dcf.png)

**Expected behavior**
it should just accept that there are no rows, and continue.

version: V1.6.0

**Comment by NickBelhomme** [comment]
Issue is when wrongfully returning empty rows instead of  

```
mockRead.ExpectQuery(".*").WillReturnError(sql.ErrNoRows)
```

as the real call is a QueryRow instead of Query.

So the error message could have been prettier, but in the end it is a wrongful test.

**Comment by pashagolub** [comment]
Thanks for your help. Do you have any idea how we can improve the error message?
