### ISSUE TITLE
Support CopyTo

### ISSUE THREAD

**Issue by pengux** [pashagolub/pgxmock#79]
**Is your feature request related to a problem? Please describe.**
Currently there is support for `CopyFrom` but no support for [`CopyTo`](https://pkg.go.dev/github.com/jackc/pgconn#PgConn.CopyTo)

**Describe the solution you'd like**
Allow an expectation for the `CopyTo` function

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

I'm happy to provide a PR for this.

**Comment by pashagolub** [comment]
Hello.

Package `pgconn` is a low-level PostgreSQL database driver. It operates at nearly the same level as the C library libpq. `pgxmock` is working on the level of [pgx](https://pkg.go.dev/github.com/jackc/pgx) toolkit.

The nearest possible method is [CopyToWriter](https://pkg.go.dev/github.com/jackc/pgx#Conn.CopyToWriter). Do you want to mock this method? PRs are always welcome, of course!

Thanks a lot for your interest in `pgxmock` library!

**Comment by pengux** [comment]
I think it's just unfortunate that the `CopyTo` is currently only available in the `pgconn` package and not exposed in the `pgx` the same way `CopyFrom` is. I guess let's wait until it is exposed in the same way then we can add support for it.
