### ISSUE TITLE
PgConn method

### ISSUE THREAD

**Issue by jsnb-devoted** [pashagolub/pgxmock#88]
**Is your feature request related to a problem? Please describe.**
Very similar to: https://github.com/pashagolub/pgxmock/issues/85
We use the `PgConn` method so it has to be included in our interface. Without that method being implemented we can't use the pgxmock conn

**Describe the solution you'd like**
Adding a stub for the method until someone actually needs to testing something with it.

**Describe alternatives you've considered**
I opened a PR and tested it out in our repo:
https://github.com/pashagolub/pgxmock/pull/87
Got a simple test passing 

**Additional context**

**Comment by pashagolub** [comment]
closed by #87
