### ISSUE TITLE
PgxPoolIface is missing AcquireAllIdel

### ISSUE THREAD

**Issue by fgm** [pashagolub/pgxmock#96]
**Is your feature request related to a problem? Please describe.**

I needed to create a mock pool, on which a function calls `pool.AcquireAllIdle()`. That function is a custom implementation for `pool.Reset()`, which exists in pgx v3 and v5, but [is missing in v4](https://github.com/jackc/pgx/issues/1235).

**Describe the solution you'd like**

Add the method to the `PgxPoolIface`

**Describe alternatives you've considered**

Hand-write a mock for that test case.

**Additional context**

**Comment by pashagolub** [comment]
Thanks for your request. I will start shortly pgx v5 support implementation. So I'll close this issue as "soon be deprecated"

**Comment by fgm** [comment]
Thanks for taking the time to answer, even if neegatively.

**Comment by pashagolub** [comment]
It's not a negative answer. Quite the opposite, I will support `Reset()` from v5, so we can skip this workaround from v4
